version: '3.8' # Docker Compose file version

services:
  app:  # Flask application container
    build: . # Build from Dockerfile in the current directory
    ports:
      - "8080:8080" # Map container port 8080 to host port 8080
    
    environment:

      # Pass environment variables used by the Flask app
      - DB_HOST=db
      - DB_NAME=delfin-db
      - DB_USER=delfin-user
      - DB_PASS=delfin-pass

    depends_on:
      - db # Wait forr the db service before starting the app

  db: # PostgreSQL database service
    image: postgres:13 # Use official Postgress image
    restart: always # Restart automatically on failure
    environment:
      # Set environment variables for PostgreSQL / Configure initial db, user, and password
      - POSTGRES_DB=delfin-db
      - POSTGRES_USER=delfin-user
      - POSTGRES_PASSWORD=delfin-pass
    volumes:
      - pgdata:/var/lib/postgresql/data # Persist data in named volume
    
volumes:
  pgdata: # Declare persistent volume for PostgreSQL data
