name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  test: # Run tests before building the Docker image
    runs-on: ubuntu-latest

    steps: # Steps to run tests
      - name: Checkout code # Checkout the repository
        uses: actions/checkout@v3 # Use the latest checkout action

      - name: Set up Python # Set up Python environment
        uses: actions/setup-python@v4 # Specify Python version
        with: # Set Python version
          python-version: '3.11' # Use Python 3.11

      - name: Install dependencies # Install required Python packages
        run: | # Install dependencies
          pip install -r requirements.txt

      - name: Run tests # Execute tests using pytest
        run: | # Run tests
          pytest

  build:
    needs: test # Ensure tests pass before building the image
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps: # Steps to build and push the Docker image
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub # Authenticate with Docker Hub
        uses: docker/login-action@v2 # Log in to Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Use secret for Docker username
          password: ${{ secrets.DOCKER_PASSWORD }} # Use secret for Docker password

      - name: Build and push Docker image # Build the Docker image and push it to Docker Hub
        uses: docker/build-push-action@v5 # Use the build-push action
        with: # Configuration for building and pushing
          context: . # Build from the current directory
          push: true # Push the image to Docker Hub
          tags: grandemeks/docker-delfin:latest # Tag the image with latest